### PR TITLE
Prevents already added tags from showing in typeahead

### PR DESCRIPTION
**Pull request by absolute-quantum**

### CODE REVIEW

**Comment by absolute-quantum** [comment]
@mbrochh @wmbenedetto @Tyrdall @dkaufhold anyone alive :)?

**Comment by Tyrdall** [comment]
Sorry @michaeldegroot !

@dkaufhold Can you please review this?

**Comment by dkaufhold** [comment]
@michaeldegroot Sorry, I missed the message somehow 🙂 

Thank you very much for the update!

**Comment by absolute-quantum** [comment]
All good :D have a nice weekend

**Pull request merged**
